### PR TITLE
Adding Organiszation Table

### PR DESCRIPTION
**Pull request by mjmilan**
Added an Entity Framework Migration to create the Organizations Table.

Please note that I have not implemented either the Resources property or the contacts property, as I'm a little unclear on precisely what is needed. They can be added later though.

Is contacts merely a List of a class providing some sort of "classificaton" in a string, and a Person object?

Is Resources merely linking to a load of blobs?

### CODE REVIEW

**Comment by mjmilan** [comment]
This was done for issue #470

**Comment by NaveenP94** [comment]
mjmilan let me understand your question better are you suggesting that instead of a table with Contacts we have something like:

List<User> MyContacts = new List<User>() ; // where the "User" is the parent level object from which a volunteer profile and organization profile inherits. 

In this case we don't store the information in a table but each instance would have a MyContacts attribute from which data could be seen for example:

MyContacts.get("Contact_1").getPhoneNum();

?

**Comment by mjmilan** [comment]
Essentially what I am proposing is a table called contacts which has a ContactId,  an OrganizationId, a PersonId, and then some sort of field to describe the association between the Organisation and the Person...  So, if this were to be a string field, it might have values like "Press Officer", "Resource Coordinator" or "Search Coordinator"...  

It might be better to have a table of common roles and use a roleId instead... 

What are your thoughts? 

Apols for brevity...  I'm sat on a train with a smartphone...

**Comment by mjmilan** [comment]
Would you like me to add my proposals for the Resources and Contacts tables into the code so it can be considered as one pull request (not a massive job...)

**Comment by tonysurma** [comment]
I will merge this in Thanks mjmilan! and if you can do separate PRs for the others then we can do each one seperately

**Pull request merged**
