### PR TITLE
Issue #608 Added a simple phone number validation

### PR DESCRIPTION
**Pull request by lhanscom**
Also fixed false positives with other validations on the registration page.

### CODE REVIEW

**Comment by BillWagner** [comment]
Thank you for contributing to our project. The changes look great. :shipit:

**Comment by BillWagner** [comment]
@lhanscom I noticed you re-opened this PR. Is it ready to merge now, or are you still adding more?

**Comment by tonysurma** [comment]
@lhanscom any update, would love to merge just want to make sure it is 'ready' from your point of view.  Thanks.

**Comment by tonysurma** [comment]
since what @BillWagner looked at looked good I am going to go ahead and merge and we can use another pull request if there was more that @lhanscom was planning on doing.  Thanks again

**Pull request merged**
