### PR TITLE
Resource now record when they were added...

### PR DESCRIPTION
**Pull request by mjmilan**
For Issue #492, I think this takes care of the 1st task.

### CODE REVIEW

**Comment by tonysurma** [comment]
@mjmilan looks like a build error, file missing in checkin perhaps?

C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(100,9): error MSB3041: Unable to create a manifest resource name for "Migrations\201604080956174_DateEnteredOnResources.resx". Could not find file 'C:\projects\crisischeckin\crisischeckin\Models\Migrations\201604080956174_DateEnteredOnResources.cs'.

**Comment by mjmilan** [comment]
Weird... 

I'm on my commute home at the moment but don't have my laptop with me... 

I'll take a look at it over the weekend... 

Martin.

**Comment by mjmilan** [comment]
It will be a missing file in the check in though, because I successfully applied the migration on my machine - rather implying that it built locally...

**Comment by mjmilan** [comment]
Whilst I think on @tonysurma , have you had much experience of merging multiple streams of development when more than one of the streams has introduced additional EF migrations? I don't think, with the pace of development here, it is something that you are likely to have had to deal with yet.

When I used to work for thebigword, we did hit this - several times. The fix we found was to merge everything to trunk as you usually would, but then to add an additional migration using the -ignoreChanges flag. 

If you do encounter any issues merging migrations, give me a nudge... (martin@mjmilan.com)

**Comment by mjmilan** [comment]
As you can see, the build does now complete correctly - it looks like some of the migration files hadn't been added to staging by Git... 

Sorry about that.

**Comment by tonysurma** [comment]
Thx!

**Pull request merged**
