### PR TITLE
Implementing Resource Entity as per #473

### PR DESCRIPTION
**Pull request by mjmilan**
@tonysurma This pull requests does away with my file based resources, and instead creates entities as per #473 

I have also created a table called ResourceTypes, and populated it with the data provided #473 in the EF context's seed method. This means that, going forward, the resource types permitted can be tracked as a simple list in this table.

### CODE REVIEW

**Comment by tonysurma** [comment]
@mjmilan it appears from the error on the build and looking at the commit that you 'edited' the migration from the last commit and that is causing the issue that 'There is already an object named 'Resource' in the database' when the migrations are run.  Does that appear to be the case to you and/or did this work locally?  Thanks again

**Comment by mjmilan** [comment]
I didn't manually edit an existing migration...  I supplied a new one.  

I did rename my OrganizationResource model to Resource, but everything appeared to go through fine...  DB worked.  

I'll have a look for you this afternoon...

**Comment by tonysurma** [comment]
Thx, I wonder if that edit triggered the change to crisischeckin/Models/Migrations/201603161244132_AddingContactsAndResources.cs I saw.

**Comment by mjmilan** [comment]
The rename of the OrganisationResource class has made changes to the crisischeckin\Models\Migrations\201603161244132_AddingContactsAndResources.cs file that were unintended. Those changes (just that file) should be rolled back...

Just trying to find how to add a corrective commit to the pull request

**Comment by mjmilan** [comment]
Try that @tonysurma

**Comment by tonysurma** [comment]
Perfect thanks @mjmilan

**Pull request merged**
