### PR TITLE
Adding OrganizationResource and Contact to the database entities.

### PR DESCRIPTION
**Pull request by mjmilan**
@tonysurma This is a pull request for the OrganizationResources table and Contact tables, as referred to in pull request #476 .

### CODE REVIEW

**Comment by tonysurma** [comment]
thanks @mjmilan for the contributions, if there is anything more info we can provide to help you continue to contribute let us know!

**Comment by mjmilan** [comment]
I have interpretted Resources here has essentially being documents - any sort of file in any sort of format... It also occurs to me that you might want to start thinking about physical resources like plant machinery, thermal cameras etc as well... That's something to think about.

I'll keep contributing, but it's a case of when I can snatch the time (today was in my lunch break from the office...)

**Comment by tonysurma** [comment]
Gotcha, we actually want to focus on the physical resources and not documents so will work to pivot what you started towards that as you said because physical resources are the key

**Comment by mjmilan** [comment]
Hmm... We need to think about what sort of information you are going to want to capture and handle...

I'd say we're looking at something like Resource Name, Qty, Resource Type (Fixed (ie Jeep) vs Consumable (ie. blankets)). You're also going to have to think about whether you want to checkin resources in much the same way as you checkin people - so you know where (which Disaster) a resource is being utilised, and when.

Clearly a lot to think about...

**Comment by tonysurma** [comment]
Thx, for right now we are looking at this as the answer to those questions #473

**Comment by mjmilan** [comment]
No problem, I'll switch them over.

**Comment by tonysurma** [comment]
Excellent, thanks!

**Pull request merged**
