### PR TITLE
Selenium tracer bullet

### PR DESCRIPTION
**Pull request by BanksySan**
Very initial set of Selenium front end tests.  Not sure if you would want to pull it in as is yet or not as there isn't really much benefit to them yet, it's a very simple first stab.

There are some bad choices in there as I'm only just figuring out the site and how views\partials etc. all play together.  Some just that it's hard to concentrate on a sunny bank holiday weekend!

In looking at it there are some code anomalies in the application code base I'd like to tidy up that would help define views and purposes.  

For example, it's the copy and paste of the navigation bar for admin and volunteer, there are only two lines different between the whole files so rather than leaving the possibility of there being two navigation bars with slightly different selectors, would it be possible to merge this functionality into a single navigation bar that would meet both requirements?

_Future tech_

Currently all the elements are being exposed as `IWebElement`, which is okay-ish for this but some re-factoring will involve defining object managers for each user control.

Once I understand the user journeys and the purposes of them then more meaningful e2e tests can be written; actually, if you suggest some simple first ones then it could set me off in the correct path.

Thanks all,

Hope all the pull requests from someone you've never spoken to before hasn't come across as jumping in too much.

Dave

### CODE REVIEW

**Comment by BillWagner** [comment]
@BanksySan Can we get these changes on a feature branch, until we validate that it works on all platforms? At that point, we should merge the branches, but I'm a bit nervous before then.

**Comment by BanksySan** [comment]
Aye, I agree.  Shall I carry on with the fork and just give you reviews or would you rather create a branch on your side and I'll create pull requests into that?

**Comment by BillWagner** [comment]
Go ahead and carry on with your fork. That should work perfectly.

**Comment by BanksySan** [comment]
Closing as carrying on in fork.

**Pull request closed without merging**
