### PR TITLE
#501 - Task/Request table Details

### PR DESCRIPTION
**Pull request by andrewhart098**
I created a new Request Model and associated database migration.  I created a Request Controller and associated views for both Admin and Volunteer users.  I then created a RequestService which houses most of the business logic for Requests. I also created associated tests for much of the Request Service.  I tried to use async as much as possible.

Here are some user stories that are included in these changes.

1. Admins can see a list of requests.
2. Admins can sort requests.
3. Admins can filter requests.
4. Admins can sort filtered requests.
5. Admins can create requests.
6. Admins can edit requests.
7. Admins can see details of requests.
8. Admins can delete requests.
9. Volunteers can see unassigned requests.
10. Volunteers can self assign requests.
11. Volunteers can complete requests.
12. Volunteers cannot see completed requests.

I had some trouble testing two async methods in my service.  They were AssignRequestAsync and CompleteRequestAsync.  Admittedly, testing is not my strong point.

I realize this is a whole pile of commits.  I believe I should be able to squash these commits into one.  Please let me know if that would be preferable.

### CODE REVIEW

**Comment by tonysurma** [comment]
@BillWagner and @NaveenP94 any chance you can take a look at this?

**Comment by NaveenP94** [comment]
taking a look at it right now

**Comment by NaveenP94** [comment]
@andrewhart098  The site now shows your contribution. Thank you. A few minor issues that I was only able to notice after it went live.

1. Consider tying request to a specific disaster. Just how the "view contacts" and "view data" pages have a initial filter for disaster and date. For request we do not necessarily need initial filter by date but we would need to filter by disaster. So request can stay organized pertinent to a specific disaster. 

2. When filtering as an admin it should allow for some fields to be left blank. For example:
we should return requests that match creation date and end date but leave description blank (in reality it will be hard to match the descriptions word for word) or maybe we just want to see request that are due by a certain date, so we leave other filter fields blank and just input desired "end date" 

Besides that it looks great and its a valuable step forward for this project!
Thank you for your contribution.

**Comment by andrewhart098** [comment]
Thanks, @NaveenP94.  As to your points..

1. Got it. I can totally see how I overlooked that aspect of the UX.  If the user has to select the appropriate disaster each time, it might make sense to have some sort of global app Disaster filter.  That way, the user can select the disaster once (say from a dropdown in the navbar) and all the data displayed pertains to that disaster. 

2. I believe you don't have to fill in all of the filter fields in the Admin's requests page.  In the filter method on the RequestService.cs, I'm building an IQueryable with a switch statement and executing the query at the end of the method.  In RequestServiceTest.cs, I'm only filtering by one field in many of the tests.  As for the Description field, I'm using a simple .Contains() Linq expression.

**Comment by NaveenP94** [comment]
@andrewhart098 so after looking into the filtering table issue, you are right you can leave fields blank and the filtering works and you can also do a partial description and that worked. However for some reason if you specify the "created on date" then it wont return any filtered results. I have been searching through your code and files that deal with filtering the requests, and it looks consistent and should not produce this bug. Let me know if you are able to login as an admin and recreate the error.

**Comment by andrewhart098** [comment]
@NaveenP94 you are right.  I will open an issue to address this bug.

**Comment by andrewhart098** [comment]
#644

**Pull request merged**
