### PR TITLE
Issue #466 - WIP - Organization Profiles

### PR DESCRIPTION
**Pull request by fuguedude**
Created as WIP because there will be several elements.

### CODE REVIEW

**Comment by fuguedude** [comment]
I just looked at the commit diff, and see the 'wall of pink' entire-file changes for a lot of files - e.g for Person.cs - which is presumably because of line endings?

I've researched and looked into it, but I don't know what to do about it. What's confusing me is that Person.cs has the same line endings (CR/LF) before and after my commit, so why is the git diff showing like this?

I committed from Visual Studio Team Explorer, and the diffs looked fine when I did.

**Comment by tonysurma** [comment]
pinging @BillWagner for any insights he might have to the diffs

**Comment by fuguedude** [comment]
I have a solution - I tried committing one of these files using GitHub Desktop, and the diff showed up fine. Hopefully this will work for all files.

So I won't commit using Visual Studio!

I suggest closing this pull request, and making a new one with the same changes.

**Comment by tonysurma** [comment]
okay, I believe you can close this pull request as it is yours and then start over.  Thanks and let us know if you need any help with that.

**Comment by fuguedude** [comment]
Thanks, I will do that.

Sent from my Windows Phone

-----Original Message-----

**Pull request closed without merging**
