### PR TITLE
Issue #466 - Organization Profiles

### PR DESCRIPTION
**Pull request by fuguedude**
Marked as WIP because there are more elements to come.

### CODE REVIEW

**Comment by fuguedude** [comment]
Assuming the changes look good, do you want to merge this now? Looking at the original issue, I think perhaps everything else is, or should be, covered by separate issues.

Things done:
- Admin access level
- Manage volunteer list - add/remove, promote/demote admin
- Contact list (as part of #468)
- Resources table (as part of #468)

Things not done:
- Tasks/Requests: I could create a table view for this, but (a) looking at the recently added functionality, it seems not to link with Organizations yet, and (b) similarly to recent discussion in #468, I can't help think some kind of 'shared' table view with 'fixed' organization/disaster Id would be the most efficient way to achieve such functionality, without repetition. I think an issue was possibly going to be created for this at some point.
- Information/Updates: This seems a distinct piece of work... I don't know if there's another issue for it.

**Comment by tonysurma** [comment]
If it looks good to you, I will review and merge (if you are done can you remove WIP in the PR title - that's our convention for 'ready to go')  Thanks!

**Comment by fuguedude** [comment]
Ok - ready for you to review and merge, thanks.

**Comment by BillWagner** [comment]
Reviewed and merging.  Looks great.
(Sorry for the delay in review, the holiday weekend and a couple other days off from the project slowed me down).

:shipit:

**Pull request merged**
