### PR TITLE
Issue #606 - "View CheckIns" link doesn't work prior to logging in

### PR DESCRIPTION
**Pull request by andrewhart098**
Added new layout page for login.  This layout page contains a navbar that only has the CrisisCheckin Logo.

### CODE REVIEW

**Comment by tonysurma** [comment]
we've merged your other item.  If you can rebase this on those changes then I can merge this one in as well.  thanks again cc @BillWagner

**Comment by andrewhart098** [comment]
I totally messed up the rebase.

**Comment by andrewhart098** [comment]
Ok, I think I got it.

**Comment by tonysurma** [comment]
Thank you @andrewhart098 for the contribution

**Comment by tonysurma** [comment]
FYI I am fixing it this now but it looks like* the new _LoginLayout.cshtml page wasn't included in the csproj so doesn't get copied in the build... I am going to fix this now.  No worries and thanks again for the contribution!

* Note it looks like it wasn't there but I haven't totally figured it out yet and sometimes things are not as they appear 😺

**Comment by tonysurma** [comment]
That was it and it is fixed now.

**Pull request merged**
