### PR TITLE
Mobile API

### PR DESCRIPTION
**Pull request by brunck**
Changes to implement a REST-like API. There is only one endpoint right now.

Added several NuGet packages to implement many of the recommendations in this [article.](http://arteksoftware.com/resilient-network-services-with-xamarin/)
Includes 
- Refit for the API definition
- Connectivity plug-in
- fusillade for request prioritization and perhaps we will use its request caching mechanism
- Polly for retry handling on exceptions
- akavache is something we might use for more thorough caching.

This is dependent on changes in PR #645. This code and the code in that PR are up to date with Xamarin release Cycle 7.
In preparation for the codeathon on 6/18/16.

@BillWagner @tonysurma James Sturtevant

### CODE REVIEW

**Comment by tonysurma** [comment]
I reset the build configuration to work for these two pull requests (but for now they just build the crisischeckinweb projects and  not the xamarin stuff) so we can verify those builds continue to work at least.  I also reran the builds for these PRs.

Before Saturday or during Saturday we should get xamarin and the api stuff integrated - in fact the api stuff should get added into crisischeckinweb etc. so we can deploy that to the azure websites just like the web code. (duplicating this comment in the other PR so we have it in both)

**Comment by tonysurma** [comment]
I just verified the API stuff is in the crisischeckinweb project (yay!) so we are good on that and the build is building/testing that (for however many tests there are there).

**Comment by BillWagner** [comment]
@brunck I just merged #645  If you can manage the conflicts on this one, I'll merge it in. Then, we should be in a good position to merge the mobile-rework branch into master.

That will be exciting, and get us ready to move forward on all fronts!

**Comment by brunck** [comment]
Ok, will do.
🎉

**Comment by brunck** [comment]
@BillWagner could you merge master into mobile-rework?
I think that will help simplify things for me to manage the conflicts via my fork.

**Comment by brunck** [comment]
@BillWagner Merged. It looks good!

**Pull request merged**
